version: "3.1"

language: en  # Specify the language as English

# Configuration for Rasa NLU.
pipeline:
  # This component splits the text into tokens (words).
  - name: WhitespaceTokenizer

  # This component converts the text into a format that can be understood by machine learning algorithms.
  - name: LexicalSyntacticFeaturizer

  # This component extracts features for the RegexFeaturizer.
  - name: RegexFeaturizer

  # This component extracts entities using regex patterns.
  - name: RegexEntityExtractor

  # This component is used to convert the text into word vectors using pre-trained embeddings.
  - name: CountVectorsFeaturizer
    OOV_token: "[UNK]"  # This will help the model deal with unknown words (e.g., misspelled words).

  # This component adds additional n-gram features to deal with character-level differences.
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4

  # This component is used for intent classification and entity extraction.
  - name: DIETClassifier
    epochs: 100
    intent_classification: True
    entity_recognition: True
    constrain_similarities: True  # Helps to reduce confusion between similar intents.
    ranking_length: 5  # Ranks the top 5 intents to handle ambiguous or multiple intent scenarios.
    use_masked_language_model: False  # Optimizes for simpler intent classification.

  # This component maps similar entities to a standard value.
  - name: EntitySynonymMapper

  # This component selects a response based on the user intent.
  - name: ResponseSelector
    epochs: 100

  # Fallback classifier to handle low-confidence predictions and ambiguous intents.
  - name: FallbackClassifier
    threshold: 0.6
    ambiguity_threshold: 0.1

# Configuration for Rasa Core.
policies:
  # Memoization policy to handle known conversation paths.
  - name: MemoizationPolicy

  # Rule policy to handle rule-based predictions.
  - name: RulePolicy
    core_fallback_action_name: "action_default_fallback"
    core_fallback_threshold: 0.5
    enable_fallback_prediction: True

  # TED policy to handle more complex dialog management with ML.
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
